### ISSUE TITLE
New account's username turns into main domain

### ISSUE THREAD

**Issue by Rayhansardar420** [InfinityFreeHosting/mofh-client#18]
Hi,in last issue I had asked about domain searching.Now it's sloved by there's a big fault there.

Now I am creating a new account.

So, I chose username as "rayhansa" and domain "rayhan.geoweb.host"

It returns a string which is the cpanel usernname. But after I login into cpanel I get the main domin as rayhansa.geoweb.host 

Rather,I should have gotten the main domain as rayhan.geoweb.host

So I kept the username field empty scince it was automatically generated. But I got errors.

Is there anything to do?????

**Comment by Grendel7** [comment]
That's how MyOwnFreeHost has currently implemented main domains with the API. 

To summarize:
- You MUST submit a username yourself (and you should store it because you'll need to submit the username for later API calls).
- The username you submitted will be used for the main domain.
- The main domain is NOT a full website domain. No website will be shown on the main domain.
- The domain you submit with the create account call will be added as an addon domain (regardless of whether it's a custom domain or a subdomain).
- The addon domain will be assigned to the main htdocs directory (unlike addon domains added manually).

So you need to submit both a username and a domain name, but you can ignore the main domain shown in VistaPanel.
