### ISSUE TITLE
Get hosting ip with mofh-client?

### ISSUE THREAD

**Issue by ghost** [InfinityFreeHosting/mofh-client#25]
I am trying Get hosting ip

**Comment by Grendel7** [comment]
I'm sorry, but I have no idea what you're asking here.

**Comment by pauladams8** [comment]
I think @zxq2233 is asking if it is possible to obtain the server IP address of a user's hosting account (185.x.x.x). 

I too am interested in obtaining this data, do you know if this is possible?

**Comment by Grendel7** [comment]
You can sort-of do this by picking a domain name which you know is on the account and then doing a DNS lookup on the domain. I generally use the "main domain" (i.e. {your submitted username}.resellerdomain.example) for this.

Maybe it can be added as a utility function to the client, but it is debatable because it's not really a function of the API, and it's not very reliable in my experience. I use the [net_dns2](https://packagist.org/packages/pear/net_dns2) library for this, but it might not be the best decision or just overkill to package it with an API client.

**Comment by pauladams8** [comment]
Yes, I'm currently doing it this way as well, but I find it unreliable because of DNS propagation, so the records can't always be obtained at signup.

Do you know of any workaround for this?

**Comment by Grendel7** [comment]
If you are having trouble with resolvers maintaining their own cache, don't use those resolvers. Which is why I use a special library rather than `gethostbyname()`, because the NetDns2 library allows you to specify which nameservers are to be queried. So you can ask Byet's nameservers directly.
