### ISSUE TITLE
How exactly do errors work with this client? Can I catch the error somehow and figure out what the error is (without using typo-littered error messages)

### ISSUE THREAD

**Issue by lavender-sys** [InfinityFreeHosting/mofh-client#45]

**Comment by Grendel7** [comment]
The only error output provided by the API are the typo littered error messages. Whether you want to show them as-is to your users or want to built processing rules for them is up to you. A previous version of the client had some message matching, but even for InfinityFree the exact filtering got changed many times for my use case alone, so I gave up trying to come up with a system which works for everyone.

**Comment by lavender-sys** [comment]
Can you provide an example of what errors could look like or how you filter them?

**Comment by Grendel7** [comment]
For some inspiration, you could check the first version of this client: https://github.com/HansAdema/mofh-client/blob/0.1/src/Exception/Builder.php It has pattern matching and example messages.

But there is a reason I dropped this feature. Generic error handling didn't work out for me, and maintaining an exhaustive list of error patterns is impossible. Now I just make sure to validate data before sending it and match and handle error messages for the specific API functions.

**Comment by lavender-sys** [comment]
> Now I just make sure to validate data before sending it and match and handle error messages for the specific API functions.

Wouldn't you still have to keep a big list of all possible errors with that? 

The first client version seems to just use strpos for finding errors. Seems like that would work.

**Comment by Grendel7** [comment]
> Wouldn't you still have to keep a big list of all possible errors with that?

No, not really. This is largely mitigated by having strong validation before sending it to the API. Sure, you could filter an error message saying .tk domains are not supported, but you can also check that the domain is not a .tk domain before sending it to the API.

The only error messages I filter are the ones which I cannot adequately check before sending the API call.

And unknown error messages are unknown and show a generic error message.

> The first client version seems to just use strpos for finding errors. Seems like that would work.

Also regular expressions.

**Comment by PlanetTheCloud** [comment]
Hi, I had a question that is related to the replies.

> The only error messages I filter are the ones which I cannot adequately check before sending the API call.

What information do you meant by this?

**Comment by Grendel7** [comment]
> What information do you meant by this?

For example, you cannot host .tk domains. You could send the createacct request to the API and get the response that .tk domains are not allowed, or you can run your own validation rules on the domain and reject .tk domains before sending them to the API at all. That way, it doesn't make sense to setup filters for .tk domain errors, because your own validation makes sure that those error never occur.

**Comment by PlanetTheCloud** [comment]
@HansAdema, what I meant is: What information that you cannot adequately check before sending the API call?

**Comment by lavender-sys** [comment]
I’m assuming by that he means errors like invalid IP address, a generic failure on MOFH’s end, or a domain being on another reseller.

**Comment by PlanetTheCloud** [comment]
@Dog2puppy I believe that the `availability` method can check if a domain is already hosted on MOFH or not, and Invalid IP Address and Generic Failures on MOFH's end is not information that we're about to send them. My question is about information that we cannot adequately check before sending.

Also if such errors occurred (Invalid IP Address, Generic Failure), do you think it's best to tell the user to try again later or our system will try again automatically?

**Comment by lavender-sys** [comment]
For my client area I just return a 500 error for pretty much every error and say to try again. That’s mostly because I was too lazy to figure out how to do automatic retries though.

**Comment by Grendel7** [comment]
I second many of the things @Dog2puppy  said. I do have a generic "we were unable to create your account, try again later" error messages for those.

Retry mechanisms are an interesting suggestion. But some errors, like when a domain is not pointing to the nameservers yet, require user action to be completed properly, which is why I prefer to try the API call once synchronously, rather than multiple times asynchronously.

The `availability` call catches a lot of errors already, but it doesn't do nameserver checks and some reseller domain checks.
