### ISSUE TITLE
Error: Name servers for domain are not valid 84572435

### ISSUE THREAD

**Issue by ibllex** [InfinityFreeHosting/mofh-client#64]
Hi there,

When I create a new user using the latest 0.9 version of the MOFH client, it gives me the error: `Error: Name servers for domain are not valid 84572435`.

I tried the old 0.7 version and it worked without problems.

Here is my code:

```php
<?php

require_once './key.php';

use \InfinityFree\MofhClient\Client;

// Create a new API client with your API credentials.
$client =new Client(API_USERNAME, API_PASSWORD);

// Create a new hosting account.
$createResponse = $client->createAccount(
    '68491739', // A unique, 8 character identifier of the account. Primarily used as internal identifier.
    'password68491739', // A password to login to the control panel, FTP and databases.
    '68491739.mydomain.com', // Initial domain of the account. Can be a subdomain or a custom domain.
    'j.e.ss.i.cam.al.lan123@gmail.com', // The email address of the user.
    'free', // The hosting plan name at MyOwnFreeHost.
);

// Check whether the request was successful.
if ($createResponse->isSuccessful()) {
    echo "Created account with username: ".$createResponse->getVpUsername();
} else {
   echo 'Failed to create account: ' . $createResponse->getMessage();
   die();
}

```

**Comment by Grendel7** [comment]
The 0.9 version of the API client is being used on InfinityFree without any problems. And while the code has changed quite a bit with the 0.8 release, the API is being called just the same.

Also, the error indicates a nameserver problem. The API client doesn't do anything with nameservers, those checks are performed entirely on the MOFH side.

So please double check the domain name you entered and triple check the nameservers you set up (both through your registrar's panel and with a separate DNS lookup), and that some time passed after changing it. If it still doesn't work then, please ask iFastNet for help, because this is not a client problem.
